### ISSUE TITLE
ROCm support for AMD Radeon PRO W6600

### ISSUE THREAD

**Issue by weeklyhao** [ROCm/ROCm-docker#105]
Hi,
If ROCm can support AMD Radeon PRO W6600? If not, is there an AMD GPU type support list ? Thanks

**Comment by serhii-nakon** [comment]
It should works with HSA_OVERRIDE_GFX_VERSION=10.3.0  https://salsa.debian.org/rocm-team/community/team-project/-/wikis/Supported-GPU-list#gfx1032

**Comment by harkgill-amd** [comment]
Hi @weeklyhao, ROCm does not currently support the W6600 though, it can still work by mimicking a different gfx architecture with the `HSA_OVERRIDE_GFX_VERSION=10.3.0` environment variable as @serhii-nakon mentioned. A complete list of supported GPUs can be found in the [System Requirements](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html#supported-gpus) page.
