### ISSUE TITLE
[Feature]: Distributing ROCm and kernel drivers in OpenShift 4.x

### ISSUE THREAD

**Issue by lohbe** [ROCm/ROCm-docker#125]
### Suggestion Description

Given the rise and popularity of container platforms like OpenShift 4.x in enterprises, there should be plans to support driver installation beyond `amdgpu-install` and package-based installations. In particular, OpenShift uses RHCOS, an `rpm-ostree` based immutable OS that does not fully conform to Linux FHS - e.g. `/var/lib/dkms` is not present in the OS. 

The ask here is to consider working with Red Hat as described in the [Driver Toolkit](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.15/html-single/specialized_hardware_and_driver_enablement/index#about-driver-toolkit_driver-toolkit) documentation to enable native OpenShift + RHCOS support. This will be a significant quality-of-life improvement over the current alternative to run a [separately managed](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.15/html/machine_management/more-rhel-compute) RHEL node (and its associated limitations) on OpenShift.

### Operating System

RHCOS

### ROCm Component

ROCk kernel driver, amdgpu-dkms

**Comment by jiridanek** [comment]
See these two projects, especially the second one

* https://github.com/ROCm/k8s-device-plugin
* https://github.com/yevgeny-shnaidman/amd-gpu-operator

**Comment by lohbe** [comment]
Thanks, the 2nd one indeed looks like what I was asking for.

**Comment by jiridanek** [comment]
https://github.com/yevgeny-shnaidman/amd-gpu-operator has now become https://instinct.docs.amd.com/projects/gpu-operator/en/main/installation/openshift-olm.html

https://issues.redhat.com/browse/TELCODOCS-1786
